# Generated by Django 2.2.7 on 2019-11-15 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('country', models.CharField(max_length=20)),
                ('language', models.CharField(max_length=30)),
                ('published', models.DateField()),
                ('duration', models.PositiveIntegerField()),
                ('actors', models.ManyToManyField(related_name='act_in_movies', to='movies.Person')),
                ('directors', models.ManyToManyField(related_name='direct_movies', to='movies.Person')),
            ],
        ),
    ]
