# Generated by Django 2.2.7 on 2019-11-18 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_movie_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='price',
            new_name='adult_price',
        ),
        migrations.AddField(
            model_name='movie',
            name='child_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='student_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
    ]
