# Generated by Django 2.2.7 on 2019-11-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_auto_20191118_2034'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cinema',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=30)),
                ('location', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='movie',
            name='cinema',
            field=models.ManyToManyField(to='movies.Cinema'),
        ),
    ]
