# Generated by Django 2.2.7 on 2019-12-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20191127_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ticket_count',
            field=models.PositiveIntegerField(default=45),
        ),
    ]
