# Generated by Django 2.2.7 on 2019-11-18 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_total_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='open', max_length=10),
        ),
    ]
