# Generated by Django 2.2.7 on 2019-11-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='customer_type',
            field=models.CharField(choices=[('ST', 'Student'), ('AD', 'Adult'), ('CH', 'Child')], default='AD', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('OP', 'Open'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], default='OP', max_length=10),
        ),
    ]
