# Generated by Django 2.2.7 on 2019-11-18 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191118_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='customer_type',
        ),
    ]
