# Generated by Django 2.2.7 on 2019-11-27 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_auto_20191127_2320'),
        ('orders', '0006_remove_order_customer_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cinema',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.Cinema'),
            preserve_default=False,
        ),
    ]
